eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-provider&config-server
  cloud.config.server.git:
                         uri: file:///Users/sunxiebin/Project/learning/spring-cloud-server-discovery/spring-cloud-starter/config-repo
server:
  port: 8081
